# Generated by Django 4.0.3 on 2022-03-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=120)),
                ('priority', models.IntegerField(default=1, max_length=2)),
                ('staff', models.CharField(max_length=10)),
                ('emergency', models.CharField(max_length=5)),
                ('time', models.TimeField(auto_now=True)),
                ('room_number', models.IntegerField(max_length=2)),
            ],
        ),
    ]
