# Generated by Django 4.0.3 on 2022-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20220304_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bell',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='bell',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
